/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
    public static void main(String[] args) {
    	String mobile = "18662606215";
    	String str = mobile.substring(0, 3)+" "+mobile.substring(3, 7)+" "+mobile.substring(7);
    	
    	
    	System.out.println(str);
	}
}
